### ISSUE TITLE
Sorting by "Upload date" missing on "Watch Later" playlist

### ISSUE THREAD

**Issue by MisterTickle** [nrednav/youtube-playlist-duration-calculator#47]
Thankyou for the lovely new version 2.1.0 today.

I was pleased to see the sorting options, but I have noticed that they are not all present. The screenshot shows sorting by Index, Duration, Channel Name, Views, and Upload date.

I mostly use this on my "Watch Later" playlist, which I use very, very heavily.
It is only showing me sort options for: Index, Duration, Channel Name, and Views. Sorting by "Upload date" is missing. But I would find it very useful.

Is this a bug?

**Comment by nrednav** [comment]
Hi @MisterTickle, yes this is expected behaviour. The Watch Later (and any other private playlist) should already have an option to sort by upload (published) date:

<img width="265" alt="image" src="https://github.com/nrednav/youtube-playlist-duration-calculator/assets/26251262/ffaa538a-f0b4-4a50-99ab-0e8abfb0a446">

Does this show up for you too?

I decided to exclude it from the sort options for private playlists because it was conflicting with this native sort option provided by YouTube.

**Comment by MisterTickle** [comment]
Ah, yes. I see them, I had missed that! Many thanks!
